### ISSUE TITLE
FAQ【常见问题】

### ISSUE THREAD

**Issue by gaboolic** [gaboolic/rime-shuangpin-fuzhuma#4]
1 如何不显示形码的辅助码：
flypy_flypy.schema.yaml中

translator:
  dictionary: flypy_flypy.extended
  enable_completion: false
  ##  默认为不超过 2 个字的候选项显示输入码；将 2 改为 0 可关闭编码提示，
  ##  改为 1 则是只显示单字的输入码，依此类推。
  translator/spelling_hints: 2

spelling_hints改为0

**Comment by gaboolic** [comment]
2 开启用, .翻页
在default.yaml
```
key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal

      # 使用,和.来翻页
      # - key_bindings:/paging_with_comma_period
      
      - key_bindings:/numbered_mode_switch
 ```

# - key_bindings:/paging_with_comma_period
改为- key_bindings:/paging_with_comma_period
