### ISSUE TITLE
方案配置中的comment_form应该是comment_format

### ISSUE THREAD

**Issue by xiaoyixiao369** [gaboolic/rime-shuangpin-fuzhuma#55]
```
chaifen:
  option_name: chaifen
  opencc_config: moqi_chaifen.json
  tips: char
  show_in_comment: true
  comment_form:
    - "xform/-/ /"

chaifen_all:
  option_name: chaifen_all
  opencc_config: moqi_chaifen_all.json
  tips: char
  show_in_comment: true
  comment_form:
    - "xform/-/ /"
```
