### ISSUE TITLE
给symbols_caps_v等文件打补丁；个别单词无法输入；字库问题

### ISSUE THREAD

**Issue by suibianzai** [gaboolic/rime-shuangpin-fuzhuma#65]
作者好，我使用的是小鹤双拼，目前碰到以下问题：
1、字库太小，比起大部分系统自带输入法，明显少了很多字，仅举几个例子：“曘”“勼”“笖”……请问是需要修改什么设置吗？还是本身字库的问题？
2、个别单词，在词库里没有的情况下，输入完整拼音后，第二个候选词无法正确显示，举例：”zi pai"（我想打的是"自派"）、“zhang guang”（张光），截图见下方。我只能一个一个字打，或者把单词加入个人词库。
![Video_2024-06-06_103926](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/e02228ed-c298-427b-95af-6d741fe663cd)
![Video_2024-06-06_103845](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/4df24b96-893f-4c22-bb1e-ca257212c8a8)
3、打补丁
1）symbols_caps_v.yaml。我参考了https://github.com/iDvel/rime-ice/issues/328 创建了symbols_caps_v.custom.yaml，尝试了以下两个方案，都不行：
```
patch:
  symbols:
    __include: symbols_caps_v:/symbols
    __patch:
#对错
      '/dc': [☐, ☑, ☒, ✅, ❌, ✓, ✕, ✔, ✖, ✗, ✘]
```
```
patch:
#对错
  symbols//dc: [☐, ☑, ☒, ✅, ❌, ✓, ✕, ✔, ✖, ✗, ✘]
```
2）flypy_flypy.extended.dict.yaml。我有一些额外的词典要导入，创建了flypy_flypy.extended.dict.custom.yaml，输入以下内容，也不行
```
patch:
  import_tables/+:
    - luna_pinyin.place
    - luna_pinyin.poetry 
    - luna_pinyin.computer
    - luna_pinyin.history
    - luna_pinyin.english  
    - luna_pinyin.sogou
    - flypy_flypy.my
```
请问要怎么给这两个文件正确打补丁？
