### ISSUE TITLE
请问如何将 `。` 设置为与 `，` 类似的行为？

### ISSUE THREAD

**Issue by CarameowCookie** [gaboolic/rime-shuangpin-fuzhuma#89]
想按下句号之后，直接上屏首候选，并在其后添加一个句号。

**Comment by gaboolic** [comment]
找到你用的方案(schema.yaml文件)里面的
```
# 快捷键
key_binder:
  import_preset: default
  bindings:
    #- { when: composing, accept: Tab, send: '[' } ## 取消注释后：tab引导辅助码
    - { when: composing, accept: Control+m, send: Return }
    - { when: composing, accept: Control+w, send: Control+BackSpace }
    - { when: has_menu, accept: semicolon, send: 2 }
    # - { when: has_menu, accept: slash, send: 3 } # 用/进行选3
    - { when: composing, accept: Control+i, send: Shift+Right }
    - { when: composing, accept: Control+o, send: Shift+Left }

    # 大小字集切换
    - { when: has_menu, accept: "Control+u", toggle: big_char_set }
    # 显示墨奇码拆分的快速开关
    - { when: has_menu, accept: "Control+p", toggle: chaifen }
    - { when: has_menu, accept: "Control+l", toggle: chaifen_all }
    - { when: has_menu, accept: "Control+e", toggle: chinese_english }


    - { match: "[a-z]{1,3}", accept: Tab,  send_sequence: "/1" }
    - { match: "[a-z]{1,3}", accept: "/",  send_sequence: "/1" }
    - { match: "[a-z]{1,3}", accept: ".",  send_sequence: "/1" }
```
把其中的` - { match: "[a-z]{1,3}", accept: ".",  send_sequence: "/1" }` 删掉即可
