### ISSUE TITLE
怎么设置设定，无需每次重启又要设置一次

### ISSUE THREAD

**Issue by awyc** [gaboolic/rime-shuangpin-fuzhuma#94]
怎么设置默认456打开 
![image](https://github.com/user-attachments/assets/204ebf6d-32e7-444f-acc4-e2f0f9da8e27)

**Comment by gaboolic** [comment]
根据rime官方文档，说是用ctrl+`打开菜单后，再选，就可以记住了

**Comment by gaboolic** [comment]
不行的话，在moqi.yaml里面改最开头
```
switches_engine:  
  switches:
    - name: ascii_mode
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: traditionalization
      states: [ 简, 繁 ]
    - name: emoji
      states: [ 💀, 😄 ]
    - name: chaifen
      states: [ 不拆, 扌斥 ]
    - name: big_char_set
      states: [ 大字集, 小字集 ]
    - name: mars
      reset: 0
      states: [ 地, 煋 ] #火星文
    - name: ascii_punct
      states: [ 。，, ．， ]
```
加上reset
 reset: 0 是第一项
 reset: 1 是第二项
