### ISSUE TITLE
请求调整根节点的__patch指令，以支持利用<方案名称>.custom.yaml来进行自定义调整。

### ISSUE THREAD

**Issue by liuchibing** [gaboolic/rime-shuangpin-fuzhuma#95]
如果直接在*.schema.yaml上更改，每次更新都会被覆盖，因此想到了用*.custom.yaml的方式来记录自定义设置，然而却发现无法生效。

经研究发现，根据 https://github.com/rime/home/wiki/Configuration#%E8%87%AA%E5%8B%95%E6%87%89%E7%94%A8%E8%A3%9C%E9%9D%AA 所说，当yaml的根节点有__patch指令时，不会自动添加*.custom.yaml作为patch，因此需要修改现有schema，在根节点__patch下手动引入*.custom.yaml，以moqi_ms方案为例：
```yaml
__patch:
  - user_dict_set/prism: moqi_ms
    add_user_dict/prism: moqi_ms
    big_char_set/prism: moqi_big_ms
  - moqi_ms.custom:/patch?
```
改成这样就能正常使用moqi_ms.custom.yaml来调整方案了。

望予以考虑，谢谢！
